name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML
        run: htmlhint index.html || true

      - name: Check JS (basic syntax)
        run: node -c script.js || true
